name: Deploy to Yandex Object Storage

on:
  push:
    branches:
      - main  # Запускать при пуше в ветку main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Укажите вашу версию Node.js

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Upload to Yandex Object Storage
        # Используем популярное и проверенное действие для S3-совместимых хранилищ
        uses: w-s-l/s3-sync-action@v2.2.0
        with:
          # Настройки для загрузки
          bucket: 'voicegen-studio-site' # <-- УКАЖИТЕ ТОЧНОЕ ИМЯ ВАШЕГО БАКЕТА
          source_dir: 'dist' # <-- Папка с собранным проектом. Если у вас 'build', измените здесь
          delete_removed: 'true' # Удалять из бакета старые файлы, которых нет в новой сборке
        env:
          # Здесь мы "подсказываем" действию, как подключиться к Яндексу
          # Оно ожидает переменные с префиксом AWS_, но мы передаем в них ваши ключи от Яндекса
          AWS_ACCESS_KEY_ID: ${{ secrets.YC_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.YC_SECRET_KEY }}
          AWS_S3_ENDPOINT: 'https://storage.yandexcloud.net'
          AWS_DEFAULT_REGION: 'ru-central1' # Этот параметр можно не менять
